### ISSUE TITLE
Changing your ign lets you bypass timeban

### ISSUE THREAD

**Issue by NML32** [VortoxyDevz/TimeBan#1]
This is a great plugin but needs some extra checks to prevent users from bypassing time bans.
Would it be possible to add IP and CID checks to prevent people from bypassing the time ban by just changing their ign?

**Comment by applqpak** [comment]
thanks for the comment! And, sorry for not seeing this until now. Yes, people can change usernames, I did not intend for it to ban the user's IP and / or ClientID. But I will make the addition now!

**Comment by applqpak** [comment]
Hey, I just replaced username ban with ClientID ban. May you please test this?

**Comment by NML32** [comment]
Thanks, I will.

**Comment by Dub-Boy** [comment]
New version works well no issues so far but if possible could you add this name-cid-reason to the time ban list? Great Job on the plugin keep up the good work dude!

**Comment by Dub-Boy** [comment]
Edit: Seems server reboot cancels the time ban, this was only just noticed during our testing.

**Comment by NML32** [comment]
Looks like banned-users.txt isn't getting written to on the server

**Comment by applqpak** [comment]
yes. right now I only have the bans saved to an array which is reset every server boot, but I also have the bans saved to a .txt file as well. I can change it so it doesn't get erased every server reboot, if you want.

**Comment by applqpak** [comment]
@NML32 hmm.. ok.

**Comment by applqpak** [comment]
@NML32 just looked at the code again. Nothing seems to be interfering with the config. Did you reboot the server?

**Comment by applqpak** [comment]
@Dub-Boy hey! Although I like this idea, I think it would cause too much spam for the end-user's screen.

**Comment by NML32** [comment]
Dub and I noticed with the change to CID it would be harder to pardon if you have multiple bans and only see cid when you run /timebanlist 

I'm not sure if there is anything you could do to improve on that.

**Comment by applqpak** [comment]
@NML32  Ah, yes! Thanks for the reminder; I'll make it display in a format like "Player Name - ClientID"

**Comment by NML32** [comment]
Would we be able to pardon by ign?
Could you display only the ign but have cid in play behind the scenes?

**Comment by NML32** [comment]
@applqpak I want to give you a big thank you for how accommodating you have been with all our suggestions and requests.

This plugin has been a great addition to our server.

**Comment by applqpak** [comment]
@NML32 Wow, this was a while ago now... Anyway, i'll probably end up re-writing this as the code is not a pretty site. Feel free to tell me what features you want it to have.

**Comment by applqpak** [comment]
https://github.com/applqpak/TimeBan
feel free to test & suggest features.

**Comment by applqpak** [comment]
[![Poggit-CI](https://poggit.pmmp.io/ci.badge/applqpak/TimeBan/TimeBan)](https://poggit.pmmp.io/ci/applqpak/TimeBan/TimeBan)

[TimeBan.zip](https://github.com/VortoxyDevz/TimeBan/files/686851/TimeBan.zip)

**Comment by applqpak** [comment]
[![Poggit-CI](https://poggit.pmmp.io/ci.badge/applqpak/TimeBan/TimeBan)](https://poggit.pmmp.io/ci/applqpak/TimeBan/TimeBan)
[TimeBan.zip](https://github.com/VortoxyDevz/TimeBan/files/686948/TimeBan.zip)
[updated]

**Comment by applqpak** [comment]
Is it cool w/ you if I closed this?

**Comment by NML32** [comment]
Yes
Thanks
